language: node_js

node_js:
  - "node"

env:
  global:
    - HUGO_VERSION=0.53
    - COMMIT_MSG="Commit ${TRAVIS_COMMIT}"

before_install:
  - wget https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xvzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mkdir -p $HOME/bin
  - cp hugo $HOME/bin/hugo

install:
  - yarn install
  - git config --global user.email "${GIT_EMAIL}"
  - git config --global user.name "${GIT_NAME}"

script:
  - ./deploy.sh "${COMMIT_MSG}" > /dev/null 2>&1
